version: '3.6'
services:

  nginx:
    restart: always
    image: nginx:1.19
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/log/:/var/log/nginx/
      - ./data/gunicorn/static:/static/:ro
      - ./data/gunicorn/media:/media/
    ports:
    - "${DEMO_HTTP_PORT:-80:80}"
    entrypoint: ["nginx", "-g", "daemon off;"]

  gunicorn:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: gunicorn-build
    environment:
      DATA_DIRECTORY: /data
    volumes:
      - ./data/gunicorn/data/:/data/
      - ./data/gunicorn/static:/static/
      - ./data/gunicorn/media:/media/
