name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create presentation
        run: |
          make revealjs
      - name: Publish presentation
        run: |
          mv _build /tmp/
          git config --global user.name 'Django Rest Framework Presentacion'
          git config --global user.email 'contacto@nekmo.com'
          git checkout --orphan presentation
          rm -rf *
          mv /tmp/_build/revealjs/* .
          git add --all
          git commit -am "Updated presentation at $(date)" || echo "Already updated"
          git push --force origin presentation
